const courseItems = [
    {
      id: 'adsadsadsadsadaa',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsadsadsada',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsadsadsadsaa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsadsadsadsafa',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsadaas',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsadsadsdaad',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsadasdassadsadsa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsadfsafsasadsadsaf',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
    {
      id: 'adsadsadssdfadfaadsada',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsaadsfasfdsdsadsadsad',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsasfasdfadsadsadsa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsadasdfassadsadsaf',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
    {
      id: 'asdfasdfsafas',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsafgsgsdgdsadsadsad',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadssdgsdgsgadsadsadsa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsasdgdsgsddsadsadsaf',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
    {
      id: 'adsadsadsasgddsgsdfdsada',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sdgsdgsdgdsfgs',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsdfsdfdsfsadsadsadsadsa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadssfsfsdfdbadsadsadsaf',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
    {
      id: 'adsadsadssfdsfsdadsada',
      title: 'C Programlama Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/c.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsasdfsdfsddsadsadsad',
      title: 'C# Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/csharp.png',
      quantity: 0,
    },
    {
      id: 'sadsadsadsadsasdfsdfsddsadsadsa',
      title: 'Typescript Eğitimi',
      price: '69',
      img: 'https://www.canboz.com/Assets/img/canboz/typescript.jpg',
      quantity: 0,
    },
    {
      id: 'adsadsadsadsadssfdsdfsdadsadsaf',
      title: 'React Eğitimi',
      price: '69 ',
      img: 'https://www.canboz.com/Assets/img/canboz/react.png',
      quantity: 0,
    },
  ];
  
  export default courseItems;